name: Build Docker Images

on:
  # run it on push to the default repository branch
  push:
    paths:
      # Run only specific bcapp folder
      - src/**
    branches:
      # Run only specific branch
      - main

  workflow_dispatch:
    inputs:
      choices:
        type: choice
        description: select folder
        options: 
        - gifting
        - template

jobs:
  generate_choices:
    runs-on: ubuntu-latest
    outputs:
      choices: ${{ steps.set_choices.outputs.choices }}

    steps:
      - name: Set Choices
        id: set_choices
        run: |
          choices=("get" "post" "patch")
          echo "choices=${choices[*]}" >> $GITHUB_OUTPUT
