name: Workflow 2

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  deploy:
    needs: Workflow 1
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: folder-artifact

      - name: Load Environment Variables
        run: |
          echo "API_KEY: $FOLDER"
