name: Build Docker Images

on:
  # run it on push to the default repository branch
  push:
    branches:
      - master
      - bcapp

  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Select project to build
        options: 
          - for folder in $GITHUB_WORKSPACE; do echo $folder; done

jobs:
  # define job to build docker image
  build-container:
    name: Build Docker image
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
        with:
          context: .
          file: ./bcapp/Dockerfile
