name: Workflow Dispatch with Loop

on:
  workflow_dispatch:
    inputs:
      iterations:
        description: 'Number of iterations'
        required: true

jobs:
  run_iterations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Iterations
        run: |
          for i in $(seq 1 ${{ github.event.inputs.iterations }}); do
            echo "Iteration: $i"
            # Add your desired commands for each iteration here
          done
