name: Workflow Dispatch with Choices

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose an option'
        required: true
        type: select
        options:
          - option1
          - option2
          - option3

jobs:
  process_choice:
    runs-on: ubuntu-latest

    steps:
      - name: Process Choice
        run: |
          chosen_option="${{ github.event.inputs.choice }}"
          echo "Chosen Option: $chosen_option"
          # Add your workflow steps based on the chosen option
