name: Deploy to ECR

on:
 
  push:
    paths:
      # Run only specific bcapp folder
      - src/**
    branches:
      # Run only specific branch
      - main

  workflow_dispatch: 

jobs:
  
  build:
    
    name: Build Image & Push to ECR
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gifting
      run: |
        pwd
        folder_names=$(find ./src  -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
        echo $folder_names
        for file in $folder_names; do docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$file-latest .;docker push $ECR_REGISTRY/$ECR_REPOSITORY:$file-latest; done
