name: Workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set folder names variable
        run: |
          pwd
          ls
          folder_names=$(find ./src  -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
          echo $folder_names

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: folder-artifact
          path: $folder_names
