name: Workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set folder names variable
        run: ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: folder-artifact
          path: $folder_names
