name: User Input

on:
  workflow_run:
    workflows: ["Choices Generator"]
    types:
      - completed

jobs:
  process_choice:
    runs-on: ubuntu-latest

    steps:
      - name: Get Choices
        id: get_choices
        uses: actions/github-script@v4
        with:
          script: |
            const choicesWorkflow = context.payload.workflow_run;
            const choicesArray = choicesWorkflow.outputs.choices;
            core.setOutput("choices", choicesArray);

      - name: User Input
        id: user_input
        run: |
          choices=(${{ steps.get_choices.outputs.choices }})
          echo "Available Choices: ${choices[*]}"
          read -p "Enter your choice: " chosen_option

      - name: Process Choice
        run: |
          choices=(${{ steps.get_choices.outputs.choices }})
          chosen_option="${{ steps.user_input.outputs.chosen_option }}"

          if [[ " ${choices[*]} " == *" $chosen_option "* ]]; then
            echo "Chosen Option: $chosen_option"
            # Add your workflow steps based on the chosen option
          else
            echo "Invalid choice: $chosen_option"
            exit 1
          fi
